[program:laravel-payment-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --queue=payments
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=application
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/laravel-payment-worker.log
stderr_logfile=/var/www/storage/logs/laravel-payment-worker.log
stopwaitsecs=3600
