[program:laravel-contract-renew-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --queue=contract-renew
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=application
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/laravel-contract-renew-worker.log
stopwaitsecs=3600
